import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';

export default defineConfig({
  integrations: [
    starlight({
      title: 'Mebaco',
      description: 'UIを組み、振る舞いを記述し、その場で動かすローカルアプリ開発環境。',
      favicon: '/favicon.svg',
      defaultLocale: 'root',
      locales: {
        root: { label: '日本語', lang: 'ja' },
      },
      logo: { src: './src/assets/mebaco-mark.svg', alt: 'Mebaco' },
      customCss: ['./src/styles/site.css'],
      tableOfContents: { minHeadingLevel: 2, maxHeadingLevel: 4 },
      sidebar: [
        { label: '製品紹介', items: [
          { slug: 'index', label: 'Mebacoとは' },
          { slug: 'concepts', label: '基本概念' },
          { slug: 'concepts/project-model', label: 'Projectの構造' },
          { slug: 'concepts/component', label: 'ComponentとRetention' },
          { slug: 'concepts/expressions-and-scope', label: '式とスコープ' },
        ] },
        { label: 'はじめる', items: [
          { slug: 'start', label: 'はじめ方' },
          { slug: 'start/install', label: 'インストール' },
          { slug: 'start/first-project', label: '最初のProject' },
        ] },
        { label: '使い方ガイド', items: [
          { slug: 'guides', label: 'ガイド一覧' },
          { slug: 'guides/build-ui', label: 'UIを組み立てる' },
          { slug: 'guides/state-and-actions', label: 'StateとAction' },
          { slug: 'guides/reuse-components', label: 'Componentを再利用する' },
          { slug: 'guides/style-app', label: 'Styleを適用する' },
          { slug: 'guides/resources-storage', label: 'ResourceとStorage' },
          { slug: 'guides/debug', label: 'デバッグする' },
          { slug: 'guides/distribute', label: 'アプリを配布する' },
        ] },
        { label: 'リファレンス', items: [
          { slug: 'reference', label: 'リファレンス概要' },
          { slug: 'reference/elements', label: '要素一覧と仕様台帳' },
          { label: '基本要素', collapsed: true, items: [
            { slug: 'reference/elements/project', label: 'Project' },
            { slug: 'reference/elements/common', label: 'Common' },
            { slug: 'reference/elements/apps', label: 'Apps' },
            { slug: 'reference/elements/launchers', label: 'Launchers' },
            { slug: 'reference/elements/launcher', label: 'Launcher' },
            { slug: 'reference/elements/app', label: 'App' },
            { slug: 'reference/elements/launch-options', label: 'Launch Options' },
            { slug: 'reference/elements/launch-arguments', label: 'Launch Arguments' },
            { slug: 'reference/elements/launch-argument', label: 'Launch Argument' },
            { slug: 'reference/elements/entry', label: 'Entry' },
            { slug: 'reference/elements/component', label: 'Component' },
            { slug: 'reference/elements/elements', label: 'Elements' },
            { slug: 'reference/elements/state', label: 'State' },
            { slug: 'reference/elements/tag', label: 'Tag' },
            { slug: 'reference/elements/text', label: 'Text' },
          ] },
          { label: 'Componentの再利用', collapsed: true, items: [
            { slug: 'reference/elements/props', label: 'Props' },
            { slug: 'reference/elements/value-prop', label: 'Value Prop' },
            { slug: 'reference/elements/component-use', label: 'Component Use' },
            { slug: 'reference/elements/slots', label: 'Slots（定義群）' },
            { slug: 'reference/elements/slot', label: 'Slot（定義）' },
            { slug: 'reference/elements/slot-use', label: 'Slot Use（表示位置）' },
            { slug: 'reference/elements/slot-contents', label: 'Slot Contents（内容群）' },
            { slug: 'reference/elements/slot-content', label: 'Slot Content（内容）' },
            { slug: 'reference/elements/retention', label: 'Retention' },
          ] },
          { label: '型定義', collapsed: true, items: [
            { slug: 'reference/elements/declares', label: 'Declares' },
            { slug: 'reference/elements/constants', label: 'Constants' },
            { slug: 'reference/elements/types', label: 'Types' },
            { slug: 'reference/elements/functions', label: 'Functions' },
            { slug: 'reference/elements/components', label: 'Components' },
            { slug: 'reference/elements/object-type', label: 'Object Type' },
            { slug: 'reference/elements/union-type', label: 'Union Type' },
            { slug: 'reference/elements/signature-type', label: 'Signature Type' },
          ] },
          { label: '値と処理', collapsed: true, items: [
            { slug: 'reference/elements/store', label: 'Store' },
            { slug: 'reference/elements/states', label: 'States' },
            { slug: 'reference/elements/variable', label: 'Variable' },
            { slug: 'reference/elements/constant', label: 'Constant' },
            { slug: 'reference/elements/function', label: 'Function' },
            { slug: 'reference/elements/action', label: 'Action' },
            { slug: 'reference/elements/effect', label: 'Effect' },
            { slug: 'reference/elements/effects', label: 'Effects' },
            { slug: 'reference/elements/transition', label: 'Transition' },
          ] },
          { label: '制御要素', collapsed: true, items: [
            { slug: 'reference/elements/conditional', label: 'Conditional（表示）' },
            { slug: 'reference/elements/control-conditional', label: 'Conditional（Procedure）' },
            { slug: 'reference/elements/if', label: 'If' },
            { slug: 'reference/elements/else-if', label: 'Else If' },
            { slug: 'reference/elements/else', label: 'Else' },
            { slug: 'reference/elements/switch', label: 'Switch（表示）' },
            { slug: 'reference/elements/control-switch', label: 'Switch（Procedure）' },
            { slug: 'reference/elements/case', label: 'Case' },
            { slug: 'reference/elements/default', label: 'Default' },
            { slug: 'reference/elements/loop', label: 'Loop（表示）' },
            { slug: 'reference/elements/promise', label: 'Promise' },
            { slug: 'reference/elements/promise-then', label: 'Then' },
            { slug: 'reference/elements/promise-catch', label: 'Catch' },
            { slug: 'reference/elements/function-procedure', label: 'Procedure' },
            { slug: 'reference/elements/function-return', label: 'Return' },
            { slug: 'reference/elements/block', label: 'Block' },
          ] },
          { label: 'ResourceとStorage', collapsed: true, items: [
            { slug: 'reference/elements/imports', label: 'Import' },
            { slug: 'reference/elements/transitions', label: 'Transitions' },
            { slug: 'reference/elements/resources', label: 'Resources' },
            { slug: 'reference/elements/directory-resource', label: 'Directory Resource' },
            { slug: 'reference/elements/text-resource', label: 'Text Resource' },
            { slug: 'reference/elements/sqlite-resource', label: 'SQLite Resource' },
            { slug: 'reference/elements/resource-imports', label: 'Resource Imports' },
            { slug: 'reference/elements/storage', label: 'Storage' },
            { slug: 'reference/elements/key-value', label: 'Key Value' },
            { slug: 'reference/elements/storage-imports', label: 'Storage Imports' },
          ] },
          { label: 'Style', collapsed: true, items: [
            { slug: 'reference/elements/styles', label: 'Styles' },
            { slug: 'reference/elements/style', label: 'Style' },
            { slug: 'reference/elements/style-params', label: 'Parameters' },
            { slug: 'reference/elements/style-param', label: 'Style Parameter' },
            { slug: 'reference/elements/style-locals', label: 'Locals' },
            { slug: 'reference/elements/style-keyframes', label: 'Keyframes' },
          ] },
          { label: 'DebugとRelease', collapsed: true, items: [
            { slug: 'reference/elements/debug', label: 'Debug' },
            { slug: 'reference/elements/debug-configurations', label: 'Configurations' },
            { slug: 'reference/elements/debug-configuration', label: 'Configuration' },
            { slug: 'reference/elements/debug-resource-bindings', label: 'Resource Bindings' },
            { slug: 'reference/elements/debug-launch-shortcuts', label: 'Launch Shortcuts' },
            { slug: 'reference/elements/debug-log', label: 'Log Settings' },
            { slug: 'reference/elements/release', label: 'Release' },
            { slug: 'reference/elements/bundles', label: 'Bundles' },
            { slug: 'reference/elements/bundle', label: 'Bundle' },
          ] },
          { slug: 'reference/expressions', label: '式・コード' },
          { slug: 'reference/types', label: '型システム' },
          { slug: 'reference/project-files', label: '保存形式とBundle' },
        ] },
        { label: 'レシピ・運用', items: [
          { slug: 'recipes', label: 'レシピ' },
          { slug: 'mcp', label: 'MCP・AI連携' },
          { slug: 'troubleshooting', label: 'トラブルシューティング' },
        ] },
        { label: '配布情報', items: [
          { slug: 'download', label: 'ダウンロード' },
          { slug: 'compatibility', label: '対応環境・互換性' },
          { slug: 'changelog', label: 'リリースノート' },
          { slug: 'legal/license', label: 'ライセンス' },
          { slug: 'legal/privacy', label: 'プライバシー' },
        ] },
      ],
    }),
  ],
});
